apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream
  labels:
    app: ingress-upstream
spec:
  selector:
    app: console-project
  ports:
    - name: 80-to-8080
      protocol: TCP
      port: 80
      targetPort: 8080
